import Head from 'next/head';
import { useState } from 'react';
import Upload from '../components/upload';
import Download from '../components/download';

export default function Home() {
  const [selected, setSelected] = useState('upload');
  const downloadSelected = selected === 'download';
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div
          className={`${
            downloadSelected ? 'bg-petit-grey' : 'bg-petit-purple'
          } w-screen h-screen`}
        >
        <div className="flex flex-col justify-items-stretch lg:flex-row h-full">
            <div
              className={`lg:w-1/2 h-full ${
                downloadSelected ? 'hidden' : 'visible'
              } lg:visible`}
            >
              <Upload />
            </div>
            <div
            className={`lg:w-1/2 h-full transition-all ${
                !downloadSelected ? 'hidden' : 'visible'
              } lg:inline`}
            >
              <Download text={'Finished the ui'} />
            </div>
            <div className="flex lg:hidden justify-around">
              <TabButton
                onClick={() => setSelected('upload')}
                text={'Upload'}
                selected={selected === 'upload'}
              />
              <TabButton
                onClick={() => setSelected('download')}
                text={'Download'}
                selected={selected === 'download'}
              />
            </div>
          </div>
        </div>
      </main>
    </div>
  );
}

interface TabButtonProps {
  text: string;
  onClick?: () => void;
  selected?: boolean;
}

const TabButton: React.FC<TabButtonProps> = ({
  text,
  selected = false,
  onClick,
}) => {
  return (
    <div
      onClick={onClick}
      className={`flex text-2xl place-items-center justify-center ${
        !selected ? 'bg-petit-light-purple' : 'bg-transparent'
      } shadow-2xl transition-all z-10 w-full text-center h-20`}
    >
      {text}
    </div>
  );
};
